config/routes.rb
WorkJournal::Application.routes.draw do
  match 'work_items/today' => 'work_items#today', :as => "todays_work_items"
  resources :work_items

  get "pages/home"

  root :to => 'work_items#today'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #guest user
  end
end

app/models/work_item.rb
class WorkItem < ActiveRecord::Base
  scope :today, lambda { where("date = ?", Date.today)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/work_items_controller.rb
class WorkItemsController < ApplicationController
  # GET /work_items
  # GET /work_items.xml
  def index
    @work_items = WorkItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @work_items }
    end
  end

  # GET /work_items/1
  # GET /work_items/1.xml
  def show
    @work_item = WorkItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @work_item }
    end
  end

  # GET /work_items/new
  # GET /work_items/new.xml
  def new
    @work_item = WorkItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @work_item }
    end
  end

  # GET /work_items/1/edit
  def edit
    @work_item = WorkItem.find(params[:id])
  end

  # POST /work_items
  # POST /work_items.xml
  def create
    @work_item = WorkItem.new(params[:work_item])

    respond_to do |format|
      if @work_item.save
        format.html { redirect_to(todays_work_items_path, :notice => 'Work item was successfully created.') }
        format.xml  { render :xml => @work_item, :status => :created, :location => @work_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @work_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /work_items/1
  # PUT /work_items/1.xml
  def update
    @work_item = WorkItem.find(params[:id])

    respond_to do |format|
      if @work_item.update_attributes(params[:work_item])
        format.html { redirect_to(@work_item, :notice => 'Work item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @work_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /work_items/1
  # DELETE /work_items/1.xml
  def destroy
    @work_item = WorkItem.find(params[:id])
    @work_item.destroy

    respond_to do |format|
      format.html { redirect_to(todays_work_items_path) }
      format.xml  { head :ok }
    end
  end
  
  def today
    @work_item = WorkItem.new
    @work_items  = WorkItem.today
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/work_items_helper.rb
module WorkItemsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Work Journal
    = stylesheet_link_tag 'blueprint/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'blueprint/print.css', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'blueprint/ie.css', :media => 'screen, projection'
    = stylesheet_link_tag 'app'
    = javascript_include_tag :defaults
    = yield :javascripts
    = csrf_meta_tag
  %body
  .container
    = render :partial => 'shared/nav'
    = yield

app/views/pages/home.html.haml
%h1 Pages#home
%p Find me in app/views/pages/home.html.haml

app/views/shared/_nav.html.haml
%ul#nav
  %li= link_to "home", root_path

app/views/work_items/_form.html.haml
= form_for(@work_item) do |f|
  - if @work_item.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@work_item.errors.count, 'error')} prohibited this user from being saved:"
      %ul
      - @work_item.errors.full_messages.each do |msg|
        %li= msg
  
  .field
    = f.label :date
    %br
    = f.date_select :date
  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :note
    %br
    = f.text_area :note

  .actions
    = f.submit

app/views/work_items/edit.html.haml
%h1= t '.title'
%p
  = link_to t('back'), work_items_path
  = link_to t('show'), @work_item
= render 'form'

app/views/work_items/index.html.haml
%h1= t('.title')
%p= link_to t('.new_work_item'), new_work_item_path

%table
  %thead
    %tr
      %th= WorkItem.human_attribute_name :date
      %th= WorkItem.human_attribute_name :title
      %th= WorkItem.human_attribute_name :note
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for work_item in @work_items
      %tr{ :class => cycle(:odd, :even) }
        %td= work_item.date
        %td= work_item.title
        %td= work_item.note
        %td.action= link_to t('show'), work_item
        %td.action= link_to t('edit'), edit_work_item_path(work_item)
        %td.action= link_to t('destroy'), work_item, :confirm => t('are_you_sure'), :method => :delete

app/views/work_items/new.html.haml
= content_for :javascripts do
  :javascript
    $(function(){
    
      $('#togglenotes').click(function(){
        $('#notes').toggle();
        return false;
      })
    })
    
= render 'form'

app/views/work_items/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), work_items_path
  = link_to t('edit'), edit_work_item_path(@work_item)

%dl
  %dt= WorkItem.human_attribute_name :date
  %dd= @work_item.date
  %dt= WorkItem.human_attribute_name :title
  %dd= @work_item.title
  %dt= WorkItem.human_attribute_name :note
  %dd= @work_item.note

app/views/work_items/today.html.haml
= content_for :javascripts do
  :javascript
    $(function(){
    
      $('#togglenotes').click(function(){
        $('#notes').toggle();
        return false;
      })
    })


= form_for(@work_item) do |f|
  - if @work_item.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@work_item.errors.count, 'error')} prohibited this user from being saved:"
      %ul
      - @work_item.errors.full_messages.each do |msg|
        %li= msg

  .field
    = f.label :title, "task"
    %br
    = f.text_area :title
  #notes.field
    .field
      = f.label :date
      %br
      = f.date_select :date

    = f.label :note
    %br
    = f.text_area :note
  
  = link_to "toggle notes", nil, :id => 'togglenotes'

  .actions
    = f.submit "add"

%h3
  Today's Tasks
%ol
- @work_items.each do |work_item|
  %li
    = work_item.title
    = link_to 'delete', work_item, :confirm => t('are_you_sure'), :method => :delete